//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Apollo.Services.SheffieldUniWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SheffieldUniCoursesSoap", Namespace="http://tempuri.org/")]
    public partial class SheffieldUniCourses : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCoursesFullDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCoursesShortDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SheffieldUniCourses() {
            this.Url = global::Apollo.Services.Properties.Settings.Default.Apollo_Services_SheffieldUniWebService_SheffieldUniCourses;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCoursesFullDetailsCompletedEventHandler GetCoursesFullDetailsCompleted;
        
        /// <remarks/>
        public event GetCoursesShortDetailsCompletedEventHandler GetCoursesShortDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get Full Details of all Courses", RequestElementName="Get Full Details of all Courses", RequestNamespace="http://tempuri.org/", ResponseElementName="Get Full Details of all CoursesResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Get Full Details of all CoursesResult")]
        public Course[] GetCoursesFullDetails() {
            object[] results = this.Invoke("GetCoursesFullDetails", new object[0]);
            return ((Course[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCoursesFullDetailsAsync() {
            this.GetCoursesFullDetailsAsync(null);
        }
        
        /// <remarks/>
        public void GetCoursesFullDetailsAsync(object userState) {
            if ((this.GetCoursesFullDetailsOperationCompleted == null)) {
                this.GetCoursesFullDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoursesFullDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCoursesFullDetails", new object[0], this.GetCoursesFullDetailsOperationCompleted, userState);
        }
        
        private void OnGetCoursesFullDetailsOperationCompleted(object arg) {
            if ((this.GetCoursesFullDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoursesFullDetailsCompleted(this, new GetCoursesFullDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get Truncated Details of all Courses", RequestElementName="Get Truncated Details of all Courses", RequestNamespace="http://tempuri.org/", ResponseElementName="Get Truncated Details of all CoursesResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Get Truncated Details of all CoursesResult")]
        public CourseId_Name[] GetCoursesShortDetails() {
            object[] results = this.Invoke("GetCoursesShortDetails", new object[0]);
            return ((CourseId_Name[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCoursesShortDetailsAsync() {
            this.GetCoursesShortDetailsAsync(null);
        }
        
        /// <remarks/>
        public void GetCoursesShortDetailsAsync(object userState) {
            if ((this.GetCoursesShortDetailsOperationCompleted == null)) {
                this.GetCoursesShortDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoursesShortDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCoursesShortDetails", new object[0], this.GetCoursesShortDetailsOperationCompleted, userState);
        }
        
        private void OnGetCoursesShortDetailsOperationCompleted(object arg) {
            if ((this.GetCoursesShortDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoursesShortDetailsCompleted(this, new GetCoursesShortDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Course {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string entryReqField;
        
        private int tarifField;
        
        private string universityField;
        
        private int nSSField;
        
        private string qulaificationField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EntryReq {
            get {
                return this.entryReqField;
            }
            set {
                this.entryReqField = value;
            }
        }
        
        /// <remarks/>
        public int Tarif {
            get {
                return this.tarifField;
            }
            set {
                this.tarifField = value;
            }
        }
        
        /// <remarks/>
        public string University {
            get {
                return this.universityField;
            }
            set {
                this.universityField = value;
            }
        }
        
        /// <remarks/>
        public int NSS {
            get {
                return this.nSSField;
            }
            set {
                this.nSSField = value;
            }
        }
        
        /// <remarks/>
        public string Qulaification {
            get {
                return this.qulaificationField;
            }
            set {
                this.qulaificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseId_Name {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetCoursesFullDetailsCompletedEventHandler(object sender, GetCoursesFullDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoursesFullDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoursesFullDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Course[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Course[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetCoursesShortDetailsCompletedEventHandler(object sender, GetCoursesShortDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoursesShortDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoursesShortDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseId_Name[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseId_Name[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591