//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Apollo.Services.SheffieldHallamWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SHUWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SHUWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAllCoursesAuthenticatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCoursesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllNamesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SHUWebService() {
            this.Url = global::Apollo.Services.Properties.Settings.Default.Apollo_Services_SheffieldHallamWebService_SHUWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCoursesAuthenticatedCompletedEventHandler GetAllCoursesAuthenticatedCompleted;
        
        /// <remarks/>
        public event GetAllCoursesCompletedEventHandler GetAllCoursesCompleted;
        
        /// <remarks/>
        public event GetAllNamesCompletedEventHandler GetAllNamesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCoursesAuthenticated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CourseList[] GetAllCoursesAuthenticated() {
            object[] results = this.Invoke("GetAllCoursesAuthenticated", new object[0]);
            return ((CourseList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCoursesAuthenticatedAsync() {
            this.GetAllCoursesAuthenticatedAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCoursesAuthenticatedAsync(object userState) {
            if ((this.GetAllCoursesAuthenticatedOperationCompleted == null)) {
                this.GetAllCoursesAuthenticatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCoursesAuthenticatedOperationCompleted);
            }
            this.InvokeAsync("GetAllCoursesAuthenticated", new object[0], this.GetAllCoursesAuthenticatedOperationCompleted, userState);
        }
        
        private void OnGetAllCoursesAuthenticatedOperationCompleted(object arg) {
            if ((this.GetAllCoursesAuthenticatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCoursesAuthenticatedCompleted(this, new GetAllCoursesAuthenticatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCourses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CourseList[] GetAllCourses() {
            object[] results = this.Invoke("GetAllCourses", new object[0]);
            return ((CourseList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCoursesAsync() {
            this.GetAllCoursesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCoursesAsync(object userState) {
            if ((this.GetAllCoursesOperationCompleted == null)) {
                this.GetAllCoursesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCoursesOperationCompleted);
            }
            this.InvokeAsync("GetAllCourses", new object[0], this.GetAllCoursesOperationCompleted, userState);
        }
        
        private void OnGetAllCoursesOperationCompleted(object arg) {
            if ((this.GetAllCoursesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCoursesCompleted(this, new GetAllCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllNames", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CourseName[] GetAllNames() {
            object[] results = this.Invoke("GetAllNames", new object[0]);
            return ((CourseName[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNamesAsync() {
            this.GetAllNamesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNamesAsync(object userState) {
            if ((this.GetAllNamesOperationCompleted == null)) {
                this.GetAllNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNamesOperationCompleted);
            }
            this.InvokeAsync("GetAllNames", new object[0], this.GetAllNamesOperationCompleted, userState);
        }
        
        private void OnGetAllNamesOperationCompleted(object arg) {
            if ((this.GetAllNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNamesCompleted(this, new GetAllNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseName {
        
        private int courseIdField;
        
        private string courseNameField;
        
        /// <remarks/>
        public int CourseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        public string courseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseList {
        
        private int courseIdField;
        
        private string courseNameField;
        
        private string entryCriteriaField;
        
        private string courseDescriptionField;
        
        private string courseContentField;
        
        /// <remarks/>
        public int CourseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntryCriteria {
            get {
                return this.entryCriteriaField;
            }
            set {
                this.entryCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public string CourseDescription {
            get {
                return this.courseDescriptionField;
            }
            set {
                this.courseDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CourseContent {
            get {
                return this.courseContentField;
            }
            set {
                this.courseContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllCoursesAuthenticatedCompletedEventHandler(object sender, GetAllCoursesAuthenticatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCoursesAuthenticatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCoursesAuthenticatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllCoursesCompletedEventHandler(object sender, GetAllCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllNamesCompletedEventHandler(object sender, GetAllNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseName[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseName[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591